### ISSUE TITLE
No such file or directory @ realpath_rec - /home/git

### ISSUE THREAD

**Issue by stephan--** [fritteli/gentoo-overlay#46]
Hi guys,

trying to install first time gitlab. Followed all steps in emerge info for a fresh install and now im stuck at emerging the config...There is indeed no /home/git directory....
Anyone a idea whats wrong here?

```
emerge --config "=www-apps/gitlab-ce-9.0.2"


Configuring pkg...

 * Checking configuration files
 * Migrating database ...
   /usr/bin/ruby /usr/bin/bundle exec rake db:migrate RAILS_ENV=production NODE_ENV=production
D, [2017-04-01T16:42:23.521652 #14156] DEBUG -- sentry: ** [Raven] No such file or directory @ realpath_rec - /home/git excluded from capture due to environment or should_capture callback
rake aborted!
Errno::ENOENT: No such file or directory @ realpath_rec - /home/git
/opt/gitlab/config/initializers/6_validations.rb:6:in `realpath'
/opt/gitlab/config/initializers/6_validations.rb:6:in `realpath'
/opt/gitlab/config/initializers/6_validations.rb:6:in `find_parent_path'
/opt/gitlab/config/initializers/6_validations.rb:34:in `block in validate_storages'
/opt/gitlab/config/initializers/6_validations.rb:19:in `each'
/opt/gitlab/config/initializers/6_validations.rb:19:in `validate_storages'
/opt/gitlab/config/initializers/6_validations.rb:41:in `<top (required)>'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
/opt/gitlab/config/environment.rb:5:in `<top (required)>'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
/opt/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
 * ERROR: www-apps/gitlab-ce-9.0.2::fritteli failed (config phase):
 *   failed to run rake db:migrate
 * 
 * Call stack:
 *     ebuild.sh, line  115:  Called pkg_config
 *   environment, line 4262:  Called exec_rake 'db:migrate'
 *   environment, line 1860:  Called die
 * The specific snippet of code:
 *   		${command}" || die "failed to run rake $@"
 * 
 * If you need support, post the output of `emerge --info '=www-apps/gitlab-ce-9.0.2::fritteli'`,
 * the complete build log and the output of `emerge -pqv '=www-apps/gitlab-ce-9.0.2::fritteli'`.
!!! When you file a bug report, please include the following information:
GENTOO_VM=  CLASSPATH="" JAVA_HOME=""
JAVACFLAGS="" COMPILER=""
and of course, the output of emerge --info =gitlab-ce-9.0.2
 * The complete build log is located at '/var/tmp/portage/www-apps/gitlab-ce-9.0.2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/www-apps/gitlab-ce-9.0.2/temp/environment'.
 * Working directory: '/var/tmp/portage/www-apps/gitlab-ce-9.0.2/homedir'
 * S: '/var/tmp/portage/www-apps/gitlab-ce-9.0.2/work/gitlab-ce-9.0.2'
```

**Comment by fritteli** [comment]
That's indeed wrong. In Gentoo (at least with this ebuild), Gitlab is installed in `/opt/gitlab` and there should be no references to `/home/git`, the default location for source-based installs.

Since I've installed Gitlab for the first time a few years ago, I haven't tested the fresh install since then. I'll see if I can find the error from the logs you provided. Thanks for reporting, I'll comment again later!

**Comment by stephan--** [comment]
Not sure of course if this was right (just want to make it work asap) but i removed the former created git user (userdel) and re-created according to the howto in the gitlab gentoo wiki
```
useradd -m -s /bin/bash -c 'Git Version Control' -d /home/git git
echo 'export PATH=$(ruby -rubygems -e "puts Gem.user_dir")/bin:/usr/local/bin:$PATH' >> /home/git/.bashrc
```
Next the config told me that there is no repository directory in /home/git which i then just created manually.
Had also some permission problem here and there plus needed to create the pg_trgm extension in my psql gitlab db but now it seems to ok....at least the config step is done now without reporting any further error.

**Comment by fritteli** [comment]
Ah, no, that's wrong :)
The home dir of the "git" user should be /var/lib/git. That user is created by the dev-vcs/gitlab-shell ebuild.

If you can, try to delete the user "git" and re-emerge dev-vcs/gitlab-shell and www-apps/gitlab-ce.I hope this should initialize everything correctly.

**Comment by stephan--** [comment]
Ok removed the git user and re-emerged dev-vcs/gitlab-shell. Start gitlab produces the follwing error in the unicorn.stderr.log
```
I, [2017-04-01T18:58:14.837144 #7565]  INFO -- : Refreshing Gem list
WARNING: This version of GitLab depends on gitlab-shell 5.0.0, but you're running Unknown. Please update gitlab-shell.
/opt/gitlab/config/initializers/6_validations.rb:6:in `realpath': No such file or directory @ realpath_rec - /home/git (Errno::ENOENT)
        from /opt/gitlab/config/initializers/6_validations.rb:6:in `realpath'
        from /opt/gitlab/config/initializers/6_validations.rb:6:in `find_parent_path'
        from /opt/gitlab/config/initializers/6_validations.rb:34:in `block in validate_storages'
        from /opt/gitlab/config/initializers/6_validations.rb:19:in `each'
        from /opt/gitlab/config/initializers/6_validations.rb:19:in `validate_storages'
        from /opt/gitlab/config/initializers/6_validations.rb:41:in `<top (required)>'
```

This gitlab is really a huge beast...

**Comment by stephan--** [comment]
More things i noticed:
It seems there are some settings which needs to be changed in the /etc/gitlab/gitlab.yml:

This is prob. the reason why it was still searching for the /home/git/...
```
    storages: # You must have at least a `default` storage path.
      default:
        #path: /home/git/repositories/
        path: /var/lib/git/repositories/
```

The paths to shell needs to be changed i guess (otherwise /etc/init.d/gitlab check print some warnings/errors):
```
  ## GitLab Shell settings
  gitlab_shell:
    #path: /usr/share/gitlab-shell/
    path: /var/lib/gitlab-shell/
    #hooks_path: /usr/share/gitlab-shell/hooks/
    hooks_path: /var/lib/gitlab-shell/hooks/
```

(Hopefully) last problems i trying to fix now (/etc/init.d/gitlab check):

```
Access to /var/lib/git/.ssh/authorized_keys: error: could not open /var/lib/git/.ssh/authorized_keys: Permission denied @ rb_sysopen - /var/lib/git/.ssh/authorized_keys
drwx------ 2 1000 1000 4096 Apr  1 08:46 /var/lib/git/.ssh
FAILED
gitlab-shell self-check failed
  Try fixing it:
  Make sure GitLab is running;
  Check the gitlab-shell configuration file:
  sudo -u git -H editor /var/lib/gitlab-shell/config.yml
  Please fix the error above and rerun the checks.
```

**Comment by stephan--** [comment]
Ok...all problems now solved i hope.

Problem was that redis was (default) configured for tcp. Switched it to sockets according to the example [here](https://github.com/NodeRedis/node_redis/issues/204). Additionally i changed the path to /var/run/redis/redis,sock with 777 permission.
After these changes the /etc/init.d/gitlab check was passed (regards gitlab-shell) but next problem was sidekiq was now searching for redit via tcp what was of course working before.

Solution: Using a resque.yml in /etc/gitlab/. I just copied the example file, re-ran the gitlab check and finally all tests are passing.

uff...
